# Generated by Django 4.2.3 on 2023-08-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="token",
            field=models.CharField(max_length=250),
        ),
    ]
