# Generated by Django 4.2.3 on 2023-09-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturations", "0002_agent_token_corporate_marchand_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="first_connection_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="pwd",
            field=models.CharField(default="", max_length=200),
        ),
    ]
