# Generated by Django 4.2.3 on 2023-07-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturations", "0003_remove_invoice_products_remove_invoice_total_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Corporate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
