# Generated by Django 4.2.3 on 2023-07-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("facturations", "0004_corporate_customer_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="corporate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="facturations.corporate",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="facturations.agent",
            ),
        ),
    ]
